version: "3"
services:
  teq:
    container_name: go-base-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db-demo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3320:3306
    volumes:
      - mysql:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]

volumes:
  mysql: